# Site settings
title: Yonaka Research
description: Developing reinforcement learning to let Yonaka play games
author: Kazumi
baseurl: ""
url: "https://github.com/K-Kazum1"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom settings
permalink: /:title/
show_excerpts: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Social links (customize these)
bluesky_username: kazooomie
github_username:  K-Kazum1
